name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12, 3.13, 3.14]

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies, including testing and coverage tools
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          # Install linting, formatting, and coverage tools
          pip install flake8 black

      # Step 4: Run linters
      - name: Run Flake8 (Linting)
        run: |
          flake8 .
      - name: Run Black (Formatting Check)
        run: |
          black --check .

      # Step 5: Set up the SQLite database
      - name: Set up SQLite database
        run: |
          python manage.py migrate  # Create the SQLite database with migrations

      # Step 6: Run tests
      - name: Run tests
        run: |
          python manage.py test
