name: Enforce PR for main branch

on:
  push:
    branches:
      - main

jobs:
  enforce-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Check if the push is from a PR
      run: |
        if [ "${{ github.event_name }}" != "pull_request" ]; then
          echo "Pushes to main branch are only allowed through a pull request."
          exit 1
        fi
